config/routes.rb
Rails.application.routes.draw do
  root to: 'jobs#home'

  resources :jobs do
    collection do
      get 'home'
      get 'city'
      get 'city/:slug', to: 'jobs#jobs_in_city'
      get 'search'
    end
  end
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cities_job.rb
class CitiesJob < ApplicationRecord
  belongs_to :job, foreign_key: 'job_id'
  belongs_to :city, foreign_key: 'city_id'
  validates :job_id, presence: true
  validates :city_id, presence: true
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
  has_many :cities_jobs,  foreign_key: 'city_id',
                          dependent: :destroy
  has_many :jobs, through: :cities_jobs

  validates :name,  presence: true, length: { maximum: 255 },
                    uniqueness: { case_sensitive: false }
  validates :city_type, length: { maximum: 255 }
  validates :slug, length: { maximum: 255 }
  validates :name_with_type, length: { maximum: 255 }
  validates :path, length: { maximum: 255 }
end

app/models/company.rb
class Company < ApplicationRecord
  has_many  :jobs, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 },
                   uniqueness: { case_sensitive: false }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :address, presence: true, length: { maximum: 255 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }

  VALID_PHONE_REGEX = /\A^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}\z/
  validates :phone, length: { maximum: 50 },
                    format: { with: VALID_PHONE_REGEX }
  validates :fax, length: { maximum: 50 }
  validates :number_of_employees, length: { maximum: 255 }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :job, foreign_key: 'job_id'
end

app/models/favorite_job.rb
class FavoriteJob < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :job, foreign_key: 'job_id'
end

app/models/industries_job.rb
class IndustriesJob < ApplicationRecord
  belongs_to :job, foreign_key: 'job_id'
  belongs_to :industry, foreign_key: 'industry_id'
  validates :job_id, presence: true
  validates :industry_id, presence: true
end

app/models/industry.rb
class Industry < ApplicationRecord
  has_many :industries_jobs,  foreign_key: 'industry_id',
                              dependent: :destroy
  has_many :jobs, through: :industries_jobs

  validates :name, presence: true, length: { maximum: 255 },
                   uniqueness: { case_sensitive: false }
end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
  belongs_to :company, foreign_key: 'company_id'

  has_many :cities_jobs,  foreign_key: 'job_id',
                          dependent: :destroy
  has_many :cities, through: :cities_jobs

  has_many :industries_jobs,  foreign_key: 'job_id',
                              dependent: :destroy
  has_many :industries, through: :industries_jobs

  has_many  :entries, dependent: :destroy
  has_many  :favorite_jobs, dependent: :destroy

  validates :title, presence: true, length: { maximum: 255 },
                    uniqueness: { case_sensitive: false }

  validates :position, presence: true, length: { maximum: 255 }
  VALID_NUMBER_REGEX = /\A((\d{0,12}(\.\d{0,2})?)|(\.\d{0,2}))\z/
  validates :salary, presence: true,
                     format: { with: VALID_NUMBER_REGEX },
                     numericality: {
                       greater_than: 0.00,
                       less_than: 999_999_999_999.99
                     }
  validates :expiry_date, presence: true
  validates :description, presence: true, length: { maximum: 1000 }
  validates :update_date, presence: true
  validates :published, presence: true, inclusion: { in: [true, false] }
  validates :welfare, presence: true, length: { maximum: 1000 }
  validates :condition, presence: true, length: { maximum: 1000 }
  validates :link, presence: true


  def self.search(search_hash = { kw: '*', page: 0})
    jobs = { job_id: [], job_num: 0 }
    solr = RSolr.connect url: Settings.solr.url
    search_params = { q: "search_text:#{search_hash[:kw]}",
                      start: search_hash[:page] * Kaminari.config.default_per_page,
                      rows: Kaminari.config.default_per_page }
    response_solr = solr.get 'select', params: search_params
    if response_solr['response']['numFound'] > 0
      jobs[:num] = response_solr['response']['numFound']
      response_solr['response']['docs'].collect do |row|
        jobs[:job_id] << row['job_id']
      end
    end
    jobs
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many  :entries, dependent: :destroy
  has_many  :favorite_jobs, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }

  validates :prefix, presence: true

  VALID_PHONE_REGEX = /\A^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}\z/
  validates :phone, length: { maximum: 50 },
                    format: { with: VALID_PHONE_REGEX }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }

  validates :password, presence: true, length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  protected

  def record_not_found
    respond_to do |format|
      format.html { render file: "#{Rails.root}/public/404",
                           layout: false,
                           status: :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

class JobsController < ApplicationController
  def index
    search_str = params[:search].blank? ? '*' : params[:search]
    job_found = Job.search(kw: search_str, page: params[:page].to_i)
    job_ids = job_found[:job_id]
    @job_num = job_found[:num]
    job_search_result = Job.where(id: job_ids)
    @jobs = Kaminari.paginate_array(job_search_result, total_count: @job_num)
                    .page(params[:page])
  end

  def show
    @job = Job.find(params[:id])
  end

  def city
    @cities = City.all.select { |city| city.jobs.any? }
  end

  def jobs_in_city
    @city = City.find_by(slug: params[:slug])
    @jobs = @city.jobs.page(params[:page])
  end

  def home
    @jobs = Job.all.order(updated_at: :desc).take(5)
    @cities = City.all.select { |city| city.jobs.any? }.take(8)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @jobs = Job.all.order(updated_at: :desc).take(5)
    @cities = City.all.take(6)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/jobs/_job.html.erb
  <div class="card" style="width: 40rem;">
    <div class="card-body">
      <h5 class="card-title"><%= job.title %></h5>
      <p class="card-text">some job description</p>
      <p>Update date: <%= time_ago_in_words(job.created_at) %> ago. </p>
      <!-- <a href="#" class="card-link">Show job</a> -->
      <%= link_to 'Show job', job, class: 'card-link' %>
    </div>
  </div>
  <br>

app/views/jobs/city.html.erb
<h3>show all <%= pluralize(@cities.count, 'city') %></h3>

<ul class='list-group'>
  <% @cities.each do |city| %>
        <li class = 'list-group-item'>
          <%= city.name %>
          <%= link_to pluralize(city.jobs.count, 'job'),
                      controller: 'jobs',
                      action: 'jobs_in_city',
                      slug: city.slug %>
        </li>
  <% end %>
</ul>

app/views/jobs/home.html.erb
<div class='container'>
  <div class='container'>
    <nav class='navbar navbar-light bg-light'>
      <%= form_tag( jobs_path,
                    method: 'get',
                    class: 'form-inline') do %>
        <%= text_field_tag :search, params[:search],
                        placeholder: 'Search Jobs',
                        class: 'form-control mr-sm-2'%>
        <%= submit_tag 'Search', name: nil,
                        class: 'btn btn-outline-success my-2 my-sm-0' %>
      <% end %>
    </nav>
  </div>

  <div class='jobs-list'>
    <ul>
      <%= render @jobs %>
    </ul>
  </div>

  <h4> Cities list </h4>
  <div class='cities-list'>
    <ul>
      <% @cities.each do |city| %>
        <li>
          <%= city.name %>
          <%= link_to pluralize(city.jobs.count, 'job'),
                      controller: 'jobs',
                      action: 'jobs_in_city',
                      slug: city.slug %>
        </li>
      <% end %>
    </ul>
  </div
</div>

app/views/jobs/index.html.erb
<h3>Search result: <%= pluralize(@job_num , 'job') %></h3>

<nav class='navbar navbar-light bg-light'>
    <%= form_tag(jobs_path, method: 'get',
                        class: 'form-inline') do %>
        <%= text_field_tag :search, params[:search],
                        placeholder: 'Search Jobs',
                        class: 'form-control mr-sm-2'%>
        <%= submit_tag 'Search', name: nil,
                        class: 'btn btn-outline-success my-2 my-sm-0' %>
    <% end %>
</nav>

  <%= paginate @jobs%>
  <%= render @jobs %>

app/views/jobs/jobs_in_city.html.erb
<h4><%= @city.name %>: <%= pluralize(@city.jobs.count, 'job') %></h4>
<div class='container'>
  <div class='jobs-list'>
    <ul>
      <%= paginate @jobs, outer_window: 3 %>
      <%= render @jobs %>
    </ul>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="row">
  <aside class="col-md-16">
    <section class="user_info">
    <h2>Job detail</h2>
    
    <h4>
      <%= @job.title %>
    </h4>

    <p>
      <%= @job.description %>
    </p>
    </section> 
  </aside>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Venjobs', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to 'City', city_jobs_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VenjobsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class='container'>
  <div class='jobs-list'>
    <ul>
      <% @jobs.each do |job| %>
        <li>
          <div class="card">
            <h5 class="card-header"><%= job.title %></h5>
            <div class="card-body">
              <h5 class="card-title"><%= job.company.name %></h5>
              <p class="card-text"><% job.description %></p>
              <%= link_to 'Show job', job, class: 'card-link' %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

  <h4> Cities list </h4>
  <div class='cities-list'>
    <ul>
      <% @cities.each do |city| %>
        <li>
          <%= city.code %> -- <%= city.name %>
          <%= link_to 'Show', controller: 'jobs', action: 'jobs_in_city', slug: city.slug %>
        </li>
      <% end %>
    </ul>
  </div
</div>